version: '3'

volumes:
  jobboard_local_postgres_data: {}
  jobboard_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: jobboard_local_django
    container_name: jobboard_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: jobboard_production_postgres
    container_name: jobboard_local_postgres
    volumes:
      - jobboard_local_postgres_data:/var/lib/postgresql/data
      - jobboard_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: jobboard_local_docs
    container_name: jobboard_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./jobboard:/app/jobboard:z
    ports:
      - '9000:9000'
    command: /start-docs

  react:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - '3000:3000'
