# Generated by Django 4.2.6 on 2023-10-19 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("company_url", models.URLField()),
                ("company_logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("location", models.CharField(max_length=100)),
                ("salary", models.PositiveIntegerField()),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("remote", models.BooleanField(default=False)),
                ("available", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
